---
version: '2.2'
services:
  synchronizer:
    build:
      context: synchronizer
    container_name: synchronizer
    environment:
      KAFKA_BROKERS: "kafka-1:19092,kafka-2:29092,kafka-3:39092"
      SCHEMA_REGISTRY_URL: "http://schema-registry:18081"
    logging:
      driver: none
